services:
  - type: web
    name: credit-score-api
    env: python
    region: oregon
    buildCommand: pip install -r backend/requirements.txt
    startCommand: gunicorn backend.app:app
    plan: free
    runtime: python
