services:
  - type: web
    name: aave-credit-score-api
    env: python
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
    plan: free
    branch: main
    runtime: python
    repo: https://github.com/adityacodes05/-Smarter-Credit-Scores-from-Blockchain-Transactions
