services:
  - type: web
    name: aave-credit-api
    env: python
    region: singapore
    plan: free
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python backend/app.py
