services:
  - type: web
    name: Smarter-Credit-Scores-from-Blockchain-Transactions
    env: python 3
    buildCommand: pip install -r requirements.txt
    startCommand: cd backend && python app.py
    region: oregon
    plan: free
